"""add liked_by to posts

Revision ID: c1bc8fdfe504
Revises: c1ea4517ff4b
Create Date: 2026-05-05 16:34:43.564871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1bc8fdfe504'
down_revision = 'c1ea4517ff4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('liked_by', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('liked_by')

    # ### end Alembic commands ###
