"""add xp badges is_admin journal entry models

Revision ID: e8940b49ee9f
Revises: c5a2d2083336
Create Date: 2026-06-01 02:01:30.855704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8940b49ee9f'
down_revision = 'c5a2d2083336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('xp', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('badges', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('badges')
        batch_op.drop_column('xp')
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
